name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run: echo "Hello World!"

    - name: Print the date
      run: date

    - name: List directory contents
      run: ls -l
